### ISSUE TITLE
VSCP bootloader client

### ISSUE THREAD

**Issue by grodansparadis** [BlueAndi/vscp-cli-tools#2]
Hi Any,

is it OK if I use some of the code from the programmer cli project in the new VSCP Works?

**Comment by BlueAndi** [comment]
Hi Ake,
yes its ok, no problem. Please consider that I updated the vscp-framework the last days, but didn't find time to update the projects yet.

Hope you were successful in finding some easter eggs the last weekend and not some in the source codes. **LOL**

**Comment by grodansparadis** [comment]
It will take some weeks still until I am there so maybe that solves itself. But I will keep that in mind. 

A lot of sugar last weekend.  No kids in the house anymore so I got it all by my self. Will probably start to shake on Wednesday when it is going out of the system. Not yet found any in the source but maybe placed a few there myself...  Home you to had a nice leave with your family  (and got some candy).

**Comment by BlueAndi** [comment]
Well you need to walk more often now around the house for (candy) compensation. Of course I got some from the girls. :-)

I updated the cli tools for the latest changes. Everything should work as expected.

**Comment by grodansparadis** [comment]
LOL. Yee that may help. Itäs a big house.

Thanks
